# To Run docker-compose up -d --force-recreate [-d = detached mode]

version: "3"
services:
  selenium:
    image: elgalu/selenium
  zalenium-hub:
    image: dosel/zalenium:latest
    hostname: zalenium
    ports: 
      - "4444:4444"
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: always
    command: >
      start --desiredContainers 5
            --maxDockerSeleniumContainers 10
            --timeZone "Eastern Time"
            --videoRecordingEnabled false
            --keepOnlyFailedTests false
            --maxTestSessions 50
    environment:
      - "zalenium_http_proxy=http://zap:8180"
      - "zalenium_https_proxy=https://zap:8180"
